site_name: Argonne Discovery Cloud SDK
site_url: https://stage.discoverycloud.anl.gov/docs/sdk
repo_url: https://github.com/AD-SDL/adc-rdm-sdk
repo_name: AD-SDL/adc-rdm-sdk

nav:
    - Home: index.md
    - Installation: installation.md
    - CLI:
        - Quick start: cli/tutorial.md
        - Command reference: cli/usage.md
    - SDK:
        - Getting started: sdk/tutorial.md
        - Usage: sdk/code_reference.md

theme: 
  name: material
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings
  - search

markdown_extensions:
    - mkdocs-typer
    - toc:
        permalink: true

