#sdk_container = sdk_adc
#name = name ${later_variable}
#
#help:
#	@echo "    hello <name>               Say hello <name> "
#	@echo "    up                         spin up docker images"
#	@echo "    stop                       stop docker images"
#	@echo "    down                       remove docker images"
#	@echo "    start                      Enter to SDK"
#
#
#hello $(later_variable):
#ifdef later_variable
#	python main.py hello $(later_variable)
#else
#	@echo ' no have a name to say hey'
#endif
