help:
	@echo "    me               		 Check you status "
	@echo "    keywords                	 Execute Query Keywords "
	@echo "    keywordsId                Execute Query Keywords by id "



me:
	python main.py me

users:
	python main.py users

user:
	python main.py user $u

samples:
	python main.py samples

sample:
	python main.py sample $u

createsample:
	python main.py createsample

studies:
	python main.py studies

study:
	python main.py study $u

createstudy:
	python main.py createstudy $v

createtest:
	python main.py createtest
createvariables:
	python main.py createvariables

createquerys:
	python main.py createquerys

investigations:
	python main.py investigations

investigation:
	python main.py investigation $u

createinvestigation:
	python main.py createinvestigation $v

customvariablesquerys:
	python main.py customvarq $v $q

auth:
	python main.py authtoken

showquerys:
	ls querys/

showvariables:
	ls variables/

setup:
	pip3 install -r requirements.txt

keywords:
	python main.py keywords

keyword:
	python main.py keyword