sdk_container = sdk_adc
name = name ${later_variable}

help:
	@echo "    hello <name>               Say hello <name> "
	@echo "    keywords                	 Execute Query Keywords "
	@echo "    keywordsId                Execute Query Keywords by id "


auth:
	python main.py authtoken

keywords:
	python main.py keywords

keyword:
	python main.py keyword

studies:
	python main.py studies

createstudy:
	python main.py createstudy $v

createvariables:
	python main.py createvariables

createquerys:
	python main.py createquerys

me:
	python main.py me

users:
	python main.py users $id

user:
	python main.py user $id

samples:
	python main.py samples

sample:
	python main.py sample $id

investigations:
	python main.py investigations

investigation:
	python main.py investigation $id

createinvestigation:
	python main.py createinvestigation $v

showquerys:
	ls querys/

showvariables:
	ls variables/
